### ISSUE TITLE
결과값 질문있습니다!

### ISSUE THREAD

**Issue by YoungEunKim99** [nawnoes/WellnessConversation-LanguageModel#11]
![결과](https://user-images.githubusercontent.com/56907015/105140460-15b03680-5b3b-11eb-881b-abcfefa34517.PNG)
안녕하세요 코드를 보고 공부하고있는 학생입니다.
공부하던 도중 질문이 있어서 issue를 올립니다!

1. answer옆에 있는 index가 카테고리의 index가 맞나요?
2. 그리고 value가 무엇을 의미하는지 궁금합니다ㅠㅠ

**Comment by nawnoes** [comment]
안녕하세요!
1. 의 경우 카테고리 index가 맞으며
2. 의 경우 softmax 결과 값을 보이려 하였고, 값이, 0~1사이의 확률 값으로 나오지 않아
다음이슈 답변과 같이 변경했습니다 [이슈](https://github.com/nawnoes/WellnessConversation-LanguageModel/issues/10#issuecomment-743198939)

감사합니다:D

**Comment by YoungEunKim99** [comment]
감사합니다!
