### ISSUE TITLE
실행방법

### ISSUE THREAD

**Issue by HwaGyeong** [nawnoes/WellnessConversation-LanguageModel#12]
안녕하세요 이 코드에서 koGPT2를 실행시켜보고 싶은데 딥러닝 공부를 처음해서 train후에 어떤 파일을 실행시켜야 하는지 모르겠습니다.
답변 주시면 감사하겠습니다.

**Comment by nawnoes** [comment]
안녕하세요.
KoGPT-2의 경우는 학습 후에 
`example/kogpt2-text-generation.py` 파일 실행으로 테스트 해보실수 있습니다.
