### ISSUE TITLE
안녕하세요, 검증 방법 질문있습니다.

### ISSUE THREAD

**Issue by Kimminjae748** [nawnoes/WellnessConversation-LanguageModel#13]
안녕하세요, 올려주신 코드로 공부해보고 있는 학생입니다. 
다름이 아니라 올려주신 train 폴더 안의 evaluate.py 파일은 kobert와 koelectra 모델의 카테고리 분류에 대한 evaluation 이라고 생각되는데요,  kogpt2 모델의 답변 생성에 대한 evaluation관련 파일은 없는지 문의드립니다. 
만약 없다면 어떤식으로 kogpt2 모델의 답변 생성을 검증하셨는지 답변 부탁드립니다.
감사합니다!

**Comment by nawnoes** [comment]
안녕하세요.
kogpt2의 경우 생성된 텍스트에 대해 평가를 하기 어려운 부분 있어
생성된 문장에 대해 추가로 검증 과정을 거치지 않았습니다. 
감사합니다!
