### ISSUE TITLE
실행과정 상에서 에러등으로 어떻게 해야할지 몰라 문의드립니다.

### ISSUE THREAD

**Issue by ryanh9801** [nawnoes/WellnessConversation-LanguageModel#15]
프로그램을 돌리려고 필요한 파일들을 확인해보고 있는데
chatbot_data.txt와 wellness_dialog.txt가 필요하다고 나와서
따로 확인하여보니 chatbot_data는 CSV 파일 형식으로 되어있고
wellness_dialog.txt는 어떤 것을 의미하는지도 모르겠습니다.

결과론적으로는 chatbot_wellness_data.txt를 생성해야 뭘 시작이라도 하지만
어떤 파일을 어떻게 처리하는지 찾아도 보이지 않아서 질문드립니다.

**Comment by ryanh9801** [comment]
마찬가지로 wellness_dialog_category.txt도 보이지 않는데 어떻게 처리해야 하나요...

**Comment by ryanh9801** [comment]
일단 wellness_dialog_category.txt의 경우 md의 예시에 맞게 따로 생성해서 문제를 해결했습니다.
다만 wellness.py에서 

Traceback (most recent call last):
  File "C:/Users/users/PycharmProjects/pythonProject3/wellness/dataloader/wellness.py", line 103, in <module>
    dataset2 = WellnessTextClassificationDataset()
  File "C:/Users/users/PycharmProjects/pythonProject3/wellness/dataloader/wellness.py", line 69, in __init__
    index_of_words = tokenizer.encode(datas[0])
AttributeError: 'NoneType' object has no attribute 'encode'

라는 에러가 나는데 어떻게 해야할가요?

**Comment by nawnoes** [comment]
안녕하세요. 
데이터의 경우 `preprocess/training_data.py`을 이용하시거나
원하시는 방법을 통해 readme.md파일에 되어있는 형식으로 학습 파일을 만드시면 됩니다.

두번째 말씀하신 에러의 경우 확인해보니 tokenizer가 None 인데 사용해서 에러가 발생한 것으로 보이고,
아래와 같이 수정하시면 사용 가능할 것으로 보입니다.  
저도 수정 후 올려두겠습니다. 
```python
      index_of_words = self.tokenizer.encode(datas[0])
      token_type_ids = [0] * len(index_of_words)
      attention_mask = [1] * len(index_of_words)
```

감사합니다~

**Comment by ryanh9801** [comment]
답변 감사합니다.
